set(ARENA_SOURCES
# main application
	arena/applicationMode.h
	arena/arena.cpp
	arena/arena_cmd.cpp
	arena/arena_ros.cpp
	arena/arena_py.cpp
	arena/arena.h
	arena/Command.cpp
	arena/Command.h
	arena/CommandRegister.h
	arena/Console.cpp
	arena/Console.h
	arena/main.cpp
	arena/physicsWorld.cpp
	arena/physicsWorld.h
	arena/level/level.cpp
	arena/level/level.h
	arena/level/levelEmpty.h
	arena/level/levelStatic.h
	arena/level/levelDynamic.h
	arena/level/levelIndustry.h
	arena/level/levelSVG.h
	arena/level/levelSVG.cpp
	arena/level/wanderer.cpp
	arena/level/wanderer.h
	arena/level/SVGFile.h
	arena/level/SVGFile.cpp
	arena/environment.cpp
	arena/environment.h
	arena/burger.h
	arena/burger.cpp
	arena/lidarCast.h
	arena/lidarCast.cpp
	arena/rectSpawn.cpp
	arena/rectSpawn.h

# engine
	engine/shader/Color2DShader.cpp
	engine/shader/Color2DShader.h
	engine/shader/Colorplex2DShader.cpp
	engine/shader/Colorplex2DShader.h
	engine/shader/particleShader.cpp
	engine/shader/particleShader.h
	engine/shader/SpriteShader.cpp
	engine/shader/SpriteShader.h
	engine/shader/TextShader.cpp
	engine/shader/TextShader.h
	engine/shader/zShaderProgram.cpp
	engine/shader/zShaderProgram.h
	engine/timer.h
	engine/camera.cpp
	engine/camera.h
	engine/f_math.cpp
	engine/f_math.h
	engine/gamePadButtonCodes.h
	engine/globalSettings.cpp
	engine/globalSettings.h
	engine/hashTable.c
	engine/hashTable.h
	engine/list.h
	engine/list.c
	engine/particleEmitter.cpp
	engine/particleEmitter.h
	engine/Quadrangle.h
	engine/renderer.cpp
	engine/renderer.h
	engine/resource.cpp
	engine/resource.h
	engine/resourceHandler.cpp
	engine/resourceHandler.h
	engine/resourceImage.cpp
	engine/settingsKeys.cpp
	engine/settingsStructs.h
	engine/Triangle.h
	engine/zColor.cpp
	engine/zColor.h
	engine/zFont.cpp
	engine/zFont.h
	engine/zFramework.cpp
	engine/zFramework.h
	engine/zGlyphMap.cpp
	engine/zGlyphMap.h
	engine/zGraphicObject.cpp
	engine/zGraphicObject.h
	engine/zLogfile.cpp
	engine/zLogfile.h
	engine/zMatrix4x4.cpp
	engine/zMatrix4x4.h
	engine/zRect.h
	engine/zSingleton.h
	engine/zStringTools.cpp
	engine/zStringTools.h
	engine/zTextView.cpp
	engine/zTextView.h
	engine/zVector2d.cpp
	engine/zVector2d.h
	engine/zVector3d.cpp
	engine/zVector3d.h
	engine/zVector4d.cpp
	engine/zVector4d.h

# additional libraries
	engine/glew/glew.c
	engine/lodepng/lodepng.cpp
)
